title:             Bergin's Blog
email:             bergin.panimayam@gmail.com
description:       My journey with Salesforce
author:            Bergin Panimayam
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://berginpanimayam.github.io"

# Social Profiles
twitter_username:  berginpanimayam
github_username:   berginpanimayam
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
